language: node_js
sudo: false
node_js:
  - 8
script:
  - npm i
  - npm run docs:build
  - $(npm bin)/macaca-ecosystem push --cwd ./docs_dist --branch gh-pages
  - npm run lint
  - npm run test
after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
