---
# 1. Initialization option
desiredCapabilities:
  platformName: 'iOS'
  deviceName: 'iPhone 6 Plus'
  app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'

#  Web Configuration
#  platformName: 'Desktop'
#  browserName: 'Chrome'
#  url: 'https://macacajs.github.io'

#  iOS Configuration
#  platformName: 'iOS'
#  deviceName: 'iPhone 6 Plus'
#  app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'

#  Android Configuration
#  isWaitActivity: true
#  activity: 'LoginActivity'
#  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'iOS'
  targetElements:
    loginAccount:
      actionType  : 2
      searchValue : 'please input username'
      actionValue : '中文+Test+12345678'
    loginPassword:
      actionType  : 2
      searchValue : 'please input password'
      actionValue : '111111'
    loginButton:
      actionType  : 1
      searchValue : 'Login'
    alertConfirm:
      actionType  : 1
      searchValue : 'yes'
  clickTypes:
    - 'StaticText'
    - 'Button'
  editTypes:
    - 'TextField'
    - 'SecureTextField'
  horizontalScrollTypes:
    - 'PageIndicator'
  verticalScrollTypes:
    - 'ScrollView'
  tabBarTypes:
    - 'TabBar'
  exclusiveTypes:
    - 'NavigationBar'
  navigationBackKeyword:
    - '返回'
    - '取消'
...


# Web Configuration
#  clickTypes:
#    - 'a'
#  editTypes:
#    - 'input'

#  # Android Configuration
#  clickTypes:
#    - 'android.widget.ImageView'
#    - 'android.widget.TextView'
#    - 'android.widget.Button'
#  editTypes:
#    - 'android.widget.EditText'
#  tabBarTypes:
#    - 'android.widget.TabWidget'

#  # iOS Configuration
#  clickTypes:
#    - 'StaticText'
#    - 'Button'
#  editTypes:
#    - 'TextField'
#    - 'SecureTextField'
#  horizontalScrollTypes:
#    - 'PageIndicator'
#  verticalScrollTypes:
#    - 'ScrollView'
#  tabBarTypes:
#    - 'TabBar'
#  exclusiveTypes:
#    - 'NavigationBar'
#  navigationBackKeyword:
#    - '返回'
#    - '取消'
