---
# 1. Initialization option
desiredCapabilities:
  platformName: 'Desktop'
  browserName: 'Electron'
  url: 'https://macacajs.github.io'

#  Web Configuration
#  platformName: 'Desktop'
#  browserName: 'Chrome'
#  url: 'https://macacajs.github.io'

#  iOS Configuration
#  platformName: 'iOS'
#  deviceName: 'iPhone 6 Plus'
#  app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'

#  Android Configuration
#  platformName: 'android'
#  isWaitActivity: true
#  activity: 'LoginActivity'
#  app: 'https://npmcdn.com/android-app-bootstrap@latest/android_app_bootstrap/build/outputs/apk/android_app_bootstrap-debug.apk'

# 2. Crawling option
crawlingConfig:
  platform: 'PC-Web'
  clickTypes:
    - 'a'
  editTypes:
    - 'input'
...

# Web Configuration
#  platform: 'PC-Web'
#  clickTypes:
#    - 'a'
#  editTypes:
#    - 'input'

#  # Android Configuration
#  platform: 'android'
#  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
#  clickTypes:
#    - 'android.widget.ImageView'
#    - 'android.widget.TextView'
#    - 'android.widget.Button'
#  editTypes:
#    - 'android.widget.EditText'
#  tabBarTypes:
#    - 'android.widget.TabWidget'

#  # iOS Configuration
#  platform: 'iOS'
#  exclusivePattern: 'pushView/popView/cookie/userAgent:/Mozilla/cookie:/setTitle/Macaca Test Swipe API/'
#  clickTypes:
#    - 'StaticText'
#    - 'Button'
#  editTypes:
#    - 'TextField'
#    - 'SecureTextField'
#  horizontalScrollTypes:
#    - 'PageIndicator'
#  verticalScrollTypes:
#    - 'ScrollView'
#  tabBarTypes:
#    - 'TabBar'
#  exclusiveTypes:
#    - 'NavigationBar'
#  navigationBackKeyword:
#    - '返回'
#    - '取消'
