---
# 1. Initialization option
desiredCapabilities:
  platformName: 'android'
    autoAcceptAlerts: false
  isWaitActivity: true
  app: 'https://npmcdn.com/ios-app-bootstrap@latest/build/ios-app-bootstrap.zip'

# 2. Crawling option
crawlingConfig:
  targetElements:
    loginAccount:
      actionType  : 2
      searchValue : 'please input username'
      actionValue : '中文+Test+12345678'
    loginPassword:
      actionType  : 2
      searchValue : 'please input password'
      actionValue : '111111'
    loginButton:
      actionType  : 1
      searchValue : 'Login'
      actionValue : ''
  exclusivePattern: 'pushView_popView_cookie'
  navigationBackKeyword:
    - '返回'
    - '取消'
...