---
# 1. Initialization option
desiredCapabilities:
  platformName: 'iOS'
  deviceName: 'iPhone 7 Plus'
  app: '/Users/Gangdooz/.macaca-temp/ios-app-bootstrap.app'
  autoAcceptAlerts: true
  reuse: 2

# 2. Crawling option
crawlingConfig:
  strategy: 'ocr'
  platform: 'ios'
  newCommandTimeout: 3
  maxActionPerPage: 10
  testingDepth: 10
  testingPeriod: 3600
  targetElements:
    confirmAlerts :
      searchValue : 'Allow'
    triggerHook:
      searchValue : 'please input username'
  exclusivePattern: 'please input password | Baidu'
...
