---
# 1. Initialization option
desiredCapabilities:
  platformName: 'iOS'
  deviceName: 'iPhone 6 Plus'
  app: '/Users/Gangdooz/.macaca-temp/xxx.app'

# 2. Crawling option
crawlingConfig:
  strategy: 'ocr'
  platform: 'ios'
  maxActionPerPage: 10
  depth: 10
  duration: 3600
  triggers:
    - see : 'Allow'
      tap : 'click'
    - see : 'OK'
      tap : 'click'
    - see : 'Enter your 4—digit MPIN'
      tap : 'click'
    - see : 'Password'
      input : '123123'
  exclude:
    - 'Baidu'
    - 'please input password'
...
