#
# Configuration for iOS
#
#---
## for full set of documentation, please refer to:
##
## 1. Initialization option
#desiredCapabilities:
#  platformName: 'iOS'
#  deviceName: 'iPhone 6 Plus'
#  app: 'https://github.com/macacajs/NoSmoke/files/2716417/ios-app-bootstrap.zip'
#
## 2. Crawling option
#crawlingConfig:
#  strategy: 'ocr'
#  platform: 'ios'
#  deviceType: 'iPhone 6 Plus'
#  triggers:
#  - 'Login'
#...

---
#
# Configuration for Android
#
# 1. Initialization option
desiredCapabilities:
  platformName: 'android'
  autoAcceptAlerts: false
  app: 'https://github.com/macacajs/NoSmoke/files/2716416/android_app_bootstrap-debug.apk.zip'

# 2. Crawling option
crawlingConfig:
  strategy: 'ocr'
  platform: 'android'
  triggers:
  - 'Login'
...
